### ISSUE TITLE
Accessing smtpHost if not defined throws an exception

### ISSUE THREAD

**Issue by QuingKhaos** [platformsh/symfonyflex-bridge#23]
`mapPlatformShSwiftmailer` throws an exception due to platformsh/config-reader-php#9 / 2.2.0 accessing `$this->smtpHost`

`platformsh/config-reader` at 2.1.0 works without problems.

```
W: PHP Fatal error:  Uncaught Platformsh\ConfigReader\NotValidPlatformException: The smtpHost variable is not defined. Are you sure you're running on Platform.sh? in /app/vendor/platformsh/config-reader/src/Config.php:515
          W: Stack trace:
          W: #0 /app/vendor/platformsh/symfonyflex-bridge/platformsh-flex-env.php(86): Platformsh\ConfigReader\Config->__get('smtpHost')
          W: #1 /app/vendor/platformsh/symfonyflex-bridge/platformsh-flex-env.php(53): Platformsh\FlexBridge\mapPlatformShSwiftmailer(Object(Platformsh\ConfigReader\Config))
          W: #2 /app/vendor/platformsh/symfonyflex-bridge/platformsh-flex-env.php(12): Platformsh\FlexBridge\mapPlatformShEnvironment()
          W: #3 /app/vendor/composer/autoload_real.php(66): require('/app/vendor/pla...')
          W: #4 /app/vendor/composer/autoload_real.php(56): composerRequire9a0d27b591e28d896c74dbafa0f17410('6e55b274997d32b...', '/app/vendor/com...')
          W: #5 /app/vendor/autoload.php(14): ComposerAutoloaderInit9a0d27b591e28d896c74dbafa0f17410::getLoader()
          W: #6 /app/vendor/helhum/typo3-console/Scripts/typo3-console.php(9): require('/app/vendo in /app/vendor/platformsh/config-reader/src/Config.php on line 515
```

**Comment by thasmo** [comment]
~@EmiiKhaos, do you mean 2.0.0 works without problems and 2.1.0 is bugged?~
Ah, nevermind - you're refering to platformsh/config-reader-php, I see.
